#!/bin/bash
#rspec spec/001_song_basics_spec.rb
#rspec spec/002_artist_basics_spec.rb
#rspec spec/003_genre_basics_spec.rb
#rspec spec/004_songs_and_artists_spec.rb
#rspec spec/005_songs_and_genres_spec.rb
#rspec spec/006_artists_and_genres_spec.rb --f-f
#rspec spec/007_findable_songs_spec.rb --f-f
#rspec spec/008_findable_module_spec.rb  --f-f
#rspec  spec/009_findable_artists_and_genres_spec.rb --f-f
#rspec spec/010_music_importer_spec.rb --f-f
#rspec spec/011_music_library_controller_spec.rb --f-f
rspec spec/012_musiclibrary_cli_spec.rb --f-f
