rvm:
 - 2.4.0
 - 2.3.3
 - 2.2.6
 - jruby-19mode
 - rbx-3
 - ruby-head
notifications:
  recipients:
    - jarmo.p@gmail.com
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: rbx-3

